apiVersion: apps/v1
kind: ConfigMap
metadata:
name: mongodb-configmap
immutable : false
data:
  username : admin
  password : password
mongodb-configmap :
storage :
  dbpath : /data/configdb
replication : 
   repilsetname : "rs0" 

