apiVersion: apps/v1
kind: secret
metadata:
name: mongodb-secret
immutable : false
data:
  username : admin
  password : password
mongodb-configmap :
storage :
  dbpath : /data/configdb
replication : 
   repilsetname : "rs0" 

